import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { MarketingChrome } from "@/components/marketing/MarketingChrome";
import { homeFooterCta } from "@/data/home";
import { btnOutline, btnPrimary } from "@/design-system/buttons";
import {
	listAllInfrastructurePaths,
	parseInfrastructureParams,
} from "@/lib/programmaticSeo";

export const revalidate = 86400;

export function generateStaticParams(): {
	city: string;
	industry: string;
}[] {
	return listAllInfrastructurePaths().map(({ city, industry }) => ({
		city,
		industry,
	}));
}

export async function generateMetadata({
	params,
}: {
	params: Promise<{ city: string; industry: string }>;
}): Promise<Metadata> {
	const { city, industry } = await params;
	const payload = parseInfrastructureParams({ city, industry });
	if (!payload) return { title: "Not found" };

	return {
		title: payload.title,
		description: payload.description,
		alternates: { canonical: payload.canonicalPath },
		openGraph: {
			title: payload.title,
			description: payload.description,
			url: `https://designedbyanthony.com${payload.canonicalPath}`,
			type: "website",
		},
	};
}

export default async function InfrastructureProgrammaticPage({
	params,
}: {
	params: Promise<{ city: string; industry: string }>;
}) {
	const { city, industry } = await params;
	const payload = parseInfrastructureParams({ city, industry });
	if (!payload) notFound();

	return (
		<MarketingChrome footerCta={homeFooterCta}>
			<section className="section-shell section-shell--wash marketing-page-hero">
				<div className="section-container">
					<p className="text-[0.72rem] font-[family-name:var(--font-inter)] uppercase tracking-[0.22em] text-[rgb(var(--accent-bronze-rgb))] mb-3">
						315 · {payload.cityLabel} · {payload.industryLabel}
					</p>
					<h1 className="page-title max-w-[44rem]">{payload.h1}</h1>
					<p className="page-lead max-w-[42rem] mt-4">{payload.lead}</p>
					<div className="flex flex-wrap gap-4 mt-10">
						<Link href="/contact" className={btnPrimary}>
							Let&apos;s build something great.
						</Link>
						<Link href="/lighthouse" className={btnOutline}>
							Audit My Site
						</Link>
					</div>
				</div>
			</section>
			<section className="section-shell">
				<div className="section-container marketing-prose max-w-[42rem]">
					<p>
						Data for this URL is generated by the shared programmatic SEO module
						and mirrored at{" "}
						<code className="text-[0.85em]">
							GET api.designedbyanthony.com/api/seo/infrastructure/
							{city}/{industry}
						</code>{" "}
						for edge-cached JSON consumption.
					</p>
				</div>
			</section>
		</MarketingChrome>
	);
}
