export const RECAPTCHA_ENTERPRISE_SITE_KEY =
	process.env.NEXT_PUBLIC_RECAPTCHA_ENTERPRISE_SITE_KEY?.trim() ||
	"6Ld4HM4sAAAAADFXc5D-i-mXlysDd8gW6RXAZeAJ";

export const RECAPTCHA_ENTERPRISE_ACTION =
	process.env.NEXT_PUBLIC_RECAPTCHA_ENTERPRISE_ACTION?.trim() || "submit";
